tap "homebrew/bundle"
tap "homebrew/core"
tap "supabase/tap"

brew "coreutils"
brew "util-linux"
brew "gcc"
brew "gh"
brew "git-extras"
brew "gnupg"
brew "neovim"
brew "rsync"
brew "shellcheck"
brew "shfmt"
brew "starship"
brew "supabase/tap/supabase"
# prefer installing deno via dockerfile
# brew "deno"
brew "xclip"
